### ISSUE TITLE
Make IO::Socket::SSL-dependent tests optional

### ISSUE THREAD

**Issue by zoffixznet** [perl6/perl6-lwp-simple#2]
Currently, attempting to install the module fails with the message below. The IO::Socket::SSL-dependent tests need to check for presence of IO::Socket::SSL before using it. 

An alternative and worse solution is to list IO::Socket::SSL in the dependencies.

```
===> Testing: LWP::Simple:ver('0.087'):auth('Cosimo Streppone')
501 Protocol scheme 'https' is only supported if IO::Socket::SSL is installed <URL:https://doc.perl6.org/type.html>

  in method request_shell at /home/zoffix/.zef/store/perl6-lwp-simple.git/f422f802ffe1ea5fa760dae859d7aeecc1edc40f/lib/LWP/Simple.pm (LWP::Simple) line 52
  in block  at /home/zoffix/.zef/store/perl6-lwp-simple.git/f422f802ffe1ea5fa760dae859d7aeecc1edc40f/lib/LWP/Simple.pm (LWP::Simple) line 98
  in method request_shell at /home/zoffix/.zef/store/perl6-lwp-simple.git/f422f802ffe1ea5fa760dae859d7aeecc1edc40f/lib/LWP/Simple.pm (LWP::Simple) line 82
  in method get at /home/zoffix/.zef/store/perl6-lwp-simple.git/f422f802ffe1ea5fa760dae859d7aeecc1edc40f/lib/LWP/Simple.pm (LWP::Simple) line 30
  in block <unit> at t/get-perl6-org.t line 17

# Looks like you planned 2 tests, but ran 1
===> Testing [FAIL]: LWP::Simple:ver('0.087'):auth('Cosimo Streppone')
```

**Comment by coke** [comment]
+1 - this breaks the install process.

**Comment by stmuk** [comment]
This is fixed.  What was previously a http test url changed to redirect to a https url which I changed to another http test url.

I don't recommend listing IO::Socket::SSL as a required dependency since this opens a can of worms to do with OpenSSL binary libraries on Rakudo Star etc.

**Comment by coke** [comment]
I'm still seeing an issue with 4991a1b72c48452273bc1ea8bdb0cd6c4a634a93:

```
$ PERL6LIB=lib prove -v -e perl6 t/custom-headers-and-content.t
t/custom-headers-and-content.t ..
1..1
501 Protocol scheme 'https' is only supported if IO::Socket::SSL is installed <URL:https://captcha.gecirtnotification.com/pitc/?url=http%3a%2f%2ffroggs%2ede%3a80%2fcgi%2dbin%2ftest%2ftest%2ecgi&referer=&reason=This+site+is+categorized+as+Miscellaneous+or+Unknown&reasoncode=CATEGORY_CAUTIONED&timebound=1&action=deny&kind=category&rule=52&cat=Miscellaneous+or+Unknown&user=200019823@ge.com&lang=en_US&zsq=P1jZrJtqfkTsMR552rJ8ZSJ4RH2fjZrJRrWfVSMzsq>

  in method request_shell at /Users/williamcoleda/sandbox/.panda-work/1469718571_1/lib/LWP/Simple.pm (LWP::Simple) line 52
  in block  at /Users/williamcoleda/sandbox/.panda-work/1469718571_1/lib/LWP/Simple.pm (LWP::Simple) line 98
  in method request_shell at /Users/williamcoleda/sandbox/.panda-work/1469718571_1/lib/LWP/Simple.pm (LWP::Simple) line 82
  in method post at /Users/williamcoleda/sandbox/.panda-work/1469718571_1/lib/LWP/Simple.pm (LWP::Simple) line 38
  in block <unit> at t/custom-headers-and-content.t line 11

# Looks like you planned 1 test, but ran 0
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 1/1 subtests

Test Summary Report
-------------------
t/custom-headers-and-content.t (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 1 tests but ran 0.
Files=1, Tests=0,  1 wallclock secs ( 0.02 usr  0.01 sys +  0.76 cusr  0.06 csys =  0.85 CPU)
Result: FAIL
```

**Comment by coke** [comment]
Closing, will open new ticket for this new issue.
